name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm ci
          npm install cypress --save-dev
          npx cypress verify

      - name: Copy test files
        run: |
          cp -r test/raw/* ./
          chmod +x ./couchbase-edge-server
          chmod +x ./resetdemo.sh

      - name: Start Edge Server
        run: |
          ./resetdemo.sh &
          sleep 30  # Wait for edge server to start

      - name: Start React App
        run: |
          npm run dev &
          sleep 30  # Wait for React app to start

      - name: Run Cypress Tests
        run: |
          npx cypress run &
          npm run test
